config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: %i[index new create show] do
    resources :reviews, only: %i[new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :delete_all

  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :category, presence: true, inclusion: { in: %w[chinese italian japanese french belgian],
                                                    message: '%{value} is not a valid category' }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true }, inclusion: { in: (0..5) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurant_path(@restaurant)
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    @review.save
    redirect_to restaurant_path(@restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Lista Mejores Restaurantes Buenos Aires</h1>
<ul>
<% @restaurants.each do |restaurant| %>
<li><%= restaurant.name %></li>
<% end %>
</ul>

app/views/restaurants/new.html.erb
<h1>Add a new restaurant</h1>

<%= simple_form_for(@restaurant) do |f| %>
<%= f.input :name %>
<%= f.input :address %>
<%= f.input :phone_number %>
<%= f.input :category, collection: %w[chinese italian japanese french belgian] %>
<%= f.submit "Add Restaurant", class: "btn btn-primary"%>
<% end %>

app/views/restaurants/show.html.erb
<h1>Restaurant Details</h1>
<h3><%= @restaurant.name %></h3>
<p><strong>Address: </strong><%= @restaurant.address %> </p>
<p><strong>Phone Number: </strong><%= @restaurant.phone_number %></p>
<p><strong>Category: </strong><%= @restaurant.category %></p>
<br>
<h2>Reviews</h2>
<% @restaurant.reviews.each do |review|%>
<p><%= review.rating %>/5 stars</p>
<p><%= review.content %></p>
<% end %>

<%= link_to "Leave a review", new_restaurant_review_path(@restaurant), class:"btn btn-primary" %>

app/views/reviews/new.html.erb
<h1>Share your review!</h1>

<%= simple_form_for [@restaurant, @review] do |f| %>
<%= f.input :rating, input_html: { min: '0', max: '5' }%>
<%= f.input :content %>
<%= f.submit "Submit Review", class: "btn btn-primary"%>
<% end %>